version: '3.9'
services:
  nginx:
    image: nginx:latest
    volumes:
    - /home/USER/nginx-configuration:/etc/nginx
    ports:
    - 80:80
    - 443:443
  ghost:
    image: ghost:latest
    ports:
    - 2368:2368
    volumes:
    - ghost-data:/var/lib/ghost/content/

volumes:
    ghost-data: